# ============================================================================
# https://www.markdownguide.org
# https://kramdown.gettalong.org/syntax.html
# ============================================================================
# if serving on https://xxx.github.io, set `baseurl: /`
# if serving on https://xxx.github.io/path, set `baseurl: /path`
baseurl: /

siteurl: https://reglue4go.github.io

# site title
title: Reglue Go
description: 'Reglue packages provide an enjoyable, expressive elegant syntax for developing applications.'
# site favicon, absolute path required
favicon: https://github.com/reglue4go.png
# home button image, absolute path requried
# avatar: https://github.com/reglue4go.png

logo: https://reglue4go.github.io/img/go/Go-Logo_Blue.svg

# Build settings
include:
  - ./assets
  - ./_data
  - ./_includes
  - ./_layouts
  - ./_posts
  - ./_sass
# defaults:
#   scope:
#     path: '' # folder to apply
#     type: 'posts' # for files in _post folder apply values
#   values:
#     layout: 'post'

# plugins:
#   - jekyll-seo-tag
